In [1]:
import pandas as pd
from sqlalchemy import create_engine
from tqdm.auto import tqdm

In [2]:
DATA_SOURCE_PREFIX = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
DATA_VERSION = 'yellow_tripdata_2021-01.csv.gz'
DTYPE = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "Float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "str",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "Float64",
    "extra": "Float64",
    "mta_tax": "Float64",
    "tip_amount": "Float64",
    "tolls_amount": "Float64",
    "improvement_surcharge": "Float64",
    "total_amount": "Float64",
    "congestion_surcharge": "Float64",
}
PARSE_DATE = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

In [3]:
# check if pandas exist
pd.__file__

'/home/s210618/projects/docker-postgresql-gcp-workshop/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [4]:
# df = pd.read_csv(DATA_SOURCE_PREFIX+DATA_VERSION, nrows=100)
df = pd.read_csv(
    DATA_SOURCE_PREFIX+DATA_VERSION,
    dtype=DTYPE,
    # nrows=100,
    parse_dates=PARSE_DATE,
)

In [5]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.1,1,N,142,43,2,8.0,3.0,0.5,0.0,0.0,0.3,11.8,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.2,1,N,238,151,2,3.0,0.5,0.5,0.0,0.0,0.3,4.3,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.7,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.6,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [6]:
df['VendorID']

0             1
1             1
2             1
3             1
4             2
           ...
1369760    <NA>
1369761    <NA>
1369762    <NA>
1369763    <NA>
1369764    <NA>
Name: VendorID, Length: 1369765, dtype: Int64

In [7]:
df['tpep_pickup_datetime']

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: datetime64[us]

In [8]:
df.dtypes

VendorID                          Int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                   Int64
trip_distance                   Float64
RatecodeID                        Int64
store_and_fwd_flag                  str
PULocationID                      Int64
DOLocationID                      Int64
payment_type                      Int64
fare_amount                     Float64
extra                           Float64
mta_tax                         Float64
tip_amount                      Float64
tolls_amount                    Float64
improvement_surcharge           Float64
total_amount                    Float64
congestion_surcharge            Float64
dtype: object

In [9]:
df.shape

(1369765, 18)

In [10]:
len(df)

1369765

In [11]:
# !uv add sqlalchemy
# !uv add psycopg2-binary

In [12]:
# create sqlalchemy engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [13]:
# Ppreview SQL statement to create table
# 1. get schema from dataframe df,
# 2. get table name from name='yellow_taxi_data',
# 3. generate "postgresql" statement based on con=engine where engine was created for postgresql database in docker
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [14]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [15]:
# create empty table with schema only (column name + dtype)
df.head(0).to_sql(
    name='yellow_taxi_data',
    con=engine,
    if_exists='replace',
)

0

In [16]:
df_iter = pd.read_csv(
    DATA_SOURCE_PREFIX+DATA_VERSION,
    dtype=DTYPE,
    parse_dates=PARSE_DATE,
    iterator=True,
    chunksize=100000,
)

In [17]:
df_iter

In [18]:
# install tqdm and from tqdm.auto import tqdm to see progress of inserting data
# !uv add tqdm

In [19]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(
        name='yellow_taxi_data',
        con=engine,
        if_exists='append'
    )

0it [00:00, ?it/s]